#!/bin/bash
#
# Custom mailer to avoid limitations of simply calling mailx.  Basically we
# want to customise the "From:".
#
# We are called via libexec/pbulk/report thus:
#
# cat ${loc}/report.txt \
#   | ${mail} -s "${report_subject_prefix} ${platform} ${build_start_iso}" \
#             ${report_recipients}
#
# and assume this will always be the case.
#

shift
subject=$1; shift
recipients=$1; shift
message=$(cat)
sendmail=/usr/sbin/sendmail

${sendmail} -oi -r"pkgsrc@example.com" -t <<EOF
From: Bulk Build User <pkgsrc@example.com>
To: ${recipients}
Subject: ${subject}

${message}
EOF
