#!/bin/bash
#
# Check to see if we need to build a pbulk bootstrap.
#

if [ $# -ne 1 ]; then
	echo "usage: $0 <pkgbuild>" 1>&2
	exit 2
else
	pkgbuild=$1; shift
fi

# Load per-pkgbuild config
. $(dirname $0)/../conf/${pkgbuild}/pkgbuild.conf

BOOTKIT="${LOCAL_PACKAGE_BASEDIR}/${BOOTSTRAP_PBULK_DIR}/${BOOTSTRAP_KIT}.tar.gz"

#
# Always build if an existing kit does not exist.
#
if [ ! -f "${BOOTKIT}" ]; then
	exit 1
fi

#
# If we're performing a bulkbuild-restart, don't rebuild the bootstrap even if
# it is out of date, to avoid nasty surprises or pointless rebuilds.
#
if [ -n "${PBULK_RESTART}" ]; then
	exit 0
fi

#
# For trunk-based builds we rebuild the bootstrap kit each time, to ensure
# there are no conflicts with bootstrap package versions being bumped.  It
# would be better if there were a way to detect this was necessary, e.g. by
# checking package versions.
#
if [[ "${pkgbuild}" =~ trunk ]]; then
	exit 1
fi
