#!/bin/bash
#
# Custom mailer to avoid limitations of simply calling mailx.  Basically we
# want to customise the "From:".
#
# We are called via libexec/pbulk/report thus:
#
# cat ${loc}/report.txt \
#   | ${mail} -s "${report_subject_prefix} ${platform} ${build_start_iso}" \
#             ${report_recipients}
#
# and assume this will always be the case.  The variables report_from_addr and
# report_from_name are exported from pbulk.conf.
#
# We are also called from scripts/run-jenkins-build, and so need to support the
# pkgbuild.conf style variables too.
#

shift
subject=$1; shift
recipients=$1; shift
message=$(cat)
sendmail=/usr/sbin/sendmail

# Support pkgbuild.conf variables when called in that context.
: ${report_from_addr:=${REPORT_FROM_ADDR}}
: ${report_from_name:=${REPORT_FROM_NAME}}

${sendmail} -oi -r"${report_from_addr}" -t <<EOF
From: ${report_from_name} <${report_from_addr}>
To: ${recipients}
Subject: ${subject}

${message}
EOF
