#!/bin/bash
#
# Custom mailer to avoid limitations of simply calling mailx.  Basically we
# want to customise the "From:".
#
# We are called via libexec/pbulk/report thus:
#
# cat ${loc}/report.txt \
#   | ${mail} -s "${report_subject_prefix} ${platform} ${build_start_iso}" \
#             ${report_recipients}
#
# and assume this will always be the case.  The variables report_from_addr and
# report_from_name are exported from pbulk.conf.
#

shift
subject=$1; shift
recipients=$1; shift
message=$(cat)
sendmail=/usr/sbin/sendmail

${sendmail} -oi -r"${report_from_addr}" -t <<EOF
From: ${report_from_name} <${report_from_addr}>
To: ${recipients}
Subject: ${subject}

${message}
EOF
