#!/bin/bash
#
# Create the final bootstrap kit for each pkgbuild.
#

usage()
{
	echo "usage: $0 [-h] [-d YYYYMMDD] <pkgbuild>" >&2
}

bootstrap_date=""
while getopts ":d:h" opt; do
	case "${opt}" in
	d)
		bootstrap_date="-${OPTARG}"
		;;
	h)
		usage
		exit
		;;
	*)
		usage
		exit 2
		;;
	esac
done
shift $((OPTIND - 1))

if [ $# -eq 1 ]; then
	pkgbuild=$1; shift
else
	usage
	exit 2
fi

# Load per-pkgbuild config
. $(dirname $0)/../conf/${pkgbuild}/pkgbuild.conf

# Helpful aliases
RELEASE_TAR="${LOCAL_PACKAGE_BASEDIR}/${BOOTSTRAP_RELEASE_DIR}/${BOOTSTRAP_KIT}${bootstrap_date}.tar.gz"
RELEASE_ASC="${RELEASE_TAR}.asc"
UPGRADE_TAR="${LOCAL_PACKAGE_BASEDIR}/${BOOTSTRAP_RELEASE_DIR}/${BOOTSTRAP_KIT}${bootstrap_date}-upgrade.tar.gz"
UPGRADE_ASC="${UPGRADE_TAR}.asc"

	#set -e
	#trap 'echo "Error : Last was $LAST"; exit' ERR
${CHROOT_CREATE} ${CHROOT_BASEDIR}/bootstrap-${pkgbuild}
/usr/sbin/chroot ${CHROOT_BASEDIR}/bootstrap-${pkgbuild} /bin/bash -c "
	PATH=${PBULK_PATH}
	${CMD_TAR} -zxf ${LOCAL_PACKAGE_BASEDIR}/${BOOTSTRAP_PBULK_DIR}/${BOOTSTRAP_KIT}.tar.gz -C /
	PATH=${PKGBUILD_LOCALBASE}/sbin:${PKGBUILD_LOCALBASE}/bin:${PBULK_PATH}
	# Ensure bootstrap packages are upgraded as well as installing extra
	# packages to ensure we use main ones and not limited bootstrap ones.
	PKG_PATH=${LOCAL_PACKAGE_BASEDIR}/${LOCAL_PACKAGE_DIR}/${binpkgpath}/All \
	    ${PKGBUILD_LOCALBASE}/sbin/pkg_add -U ${BOOTSTRAP_PACKAGES}
	# Avoid 'install' as it fails if /etc/ssl/certs exists.
	(
		cd ${PKGBUILD_SYSCONFDIR}/openssl/certs
		${PKGBUILD_LOCALBASE}/sbin/mozilla-rootcerts extract >/dev/null
		${PKGBUILD_LOCALBASE}/sbin/mozilla-rootcerts rehash >/dev/null
	)
	rm -f ${PKGBUILD_LOCALBASE}/.dlj_license_accepted
	ed ${PKGBUILD_SYSCONFDIR}/mk.conf >/dev/null 2>&1 <<-EOF
		1,5d
		i
		#
		# Configuration file for building pkgsrc packages from source.  See
		# http://pkgsrc.joyent.com/docs/building/ for more information.
		#

		.
		/^.include/
		?^.?+1
		.,$ d
		g/^TOOLS_PLATFORM/s/\?//
		g/^TOOLS_PLATFORM/s/		/	/
		w
		q
	EOF
	# SmartOS specific, keyed on PKGBUILD_GCC_REQD being set.
	if [ -n '${PKGBUILD_GCC_REQD}' ]; then
		ed ${PKGBUILD_SYSCONFDIR}/mk.conf >/dev/null 2>&1 <<-EOF
			/^PKGSRC_COMPILER/
			a
			GCC_REQD=		${PKGBUILD_GCC_REQD}
			USE_PKGSRC_GCC=		yes
			USE_PKGSRC_GCC_RUNTIME=	yes
			.
			w
			q
		EOF
	elif [ '${PKGBUILD_OPSYS}' = 'Darwin' ]; then
		ed ${PKGBUILD_SYSCONFDIR}/mk.conf >/dev/null 2>&1 <<-EOF
			a

			FETCH_USING=		curl
			MULTILIB_SUPPORTED=	no
			PKGSRC_FORTRAN=		gfortran
			X11_TYPE=		modular

			.
			r ${PKGBUILD_BASEDIR}/include/pkgoptions/osx.mk
			w
			q
		EOF
	fi
	cat >>${PKGBUILD_SYSCONFDIR}/mk.conf <<-EOF

		#
		# All local changes should go into this file, as mk.conf could
		# be replaced on upgrades.
		#
		.sinclude \"${PKGBUILD_SYSCONFDIR}/mk.conf.local\"
	EOF
	cat >>${PKGBUILD_SYSCONFDIR}/pkgin/repositories.conf <<-EOF
		#
		${REMOTE_PACKAGE_URL}/${REMOTE_PACKAGE_DIR}/All
	EOF
	cat >>${PKGBUILD_SYSCONFDIR}/pkg_install.conf <<-EOF
		GPG_KEYRING_PKGVULN=${PKGBUILD_LOCALBASE}/share/gnupg/pkgsrc-security.gpg
		PKG_PATH=${REMOTE_PACKAGE_URL}/${REMOTE_PACKAGE_DIR}/All
	EOF
	if [ -n '${PKGBUILD_GPG_SIGN_AS}' ]; then
		ed ${PKGBUILD_SYSCONFDIR}/pkg_install.conf >/dev/null 2>&1 <<-EOF
			g/^GPG=/d
			g/^GPG_SIGN_AS=/d
			/^VERIFIED_INSTALLATION=/s/=.*/=always/
			w
			q
		EOF
	fi
	sort ${PKGBUILD_SYSCONFDIR}/pkg_install.conf >/tmp/pi-$$.conf
	mv /tmp/pi-$$.conf ${PKGBUILD_SYSCONFDIR}/pkg_install.conf
	tarextras=
	ugtarextras=
	slashprivate=
	if [ -n '${PKGBUILD_GPG_SIGN_AS}' ]; then
		ugtarextras='.${PKGBUILD_SYSCONFDIR}/gnupg/pkgsrc.gpg'
	fi
	if [ '${PKGBUILD_OPSYS}' = 'Darwin' ]; then
		echo '${PKGBUILD_LOCALBASE}/sbin' >/etc/paths.d/10-pkgsrc
		echo '${PKGBUILD_LOCALBASE}/bin' >>/etc/paths.d/10-pkgsrc
		echo '${PKGBUILD_LOCALBASE}/share/man' >/etc/manpaths.d/10-pkgsrc
		tarextras='./private/etc/paths.d/10-pkgsrc ./private/etc/manpaths.d/10-pkgsrc'
		# Work around El Capitan 'Cannot extract through symlink var'.
		if [ '${PKGBUILD_VARBASE}' = '/var' ]; then
			slashprivate='/private'
		fi
	fi
	mkdir -p \${slashprivate}${PKGBUILD_VARBASE}/db/pkgin/cache
	mkdir -p ${LOCAL_PACKAGE_BASEDIR}/${BOOTSTRAP_RELEASE_DIR}
	${CMD_TAR} -zc -f ${RELEASE_TAR} -C / \
	    --exclude '.fseventsd' --exclude '.metadata_never_index' \
	    .${PKGBUILD_LOCALBASE} \
	    .\${slashprivate}${PKGBUILD_VARBASE}/db/pkgin/cache \
	    \${tarextras}
	${CMD_TAR} -zc -f ${UPGRADE_TAR} -C / \
	    --exclude '.fseventsd' --exclude '.metadata_never_index' \
	    .${PKGBUILD_SYSCONFDIR}/mk.conf \
	    .${PKGBUILD_SYSCONFDIR}/pkg_install.conf \
	    .${PKGBUILD_SYSCONFDIR}/pkgin/repositories.conf \
	    \${ugtarextras}
	if [ -n '${PKGBUILD_GPG_SIGN_AS}' ]; then
		rm -f ${RELEASE_ASC} ${UPGRADE_ASC}
		${CMD_GPG} --armor --sign --detach -u ${PKGBUILD_GPG_SIGN_AS} ${RELEASE_TAR}
		${CMD_GPG} --armor --sign --detach -u ${PKGBUILD_GPG_SIGN_AS} ${UPGRADE_TAR}
	fi
"
bsret=$?
${CHROOT_DELETE} ${CHROOT_BASEDIR}/bootstrap-${pkgbuild}
chret=$?
if [ ${bsret} -eq 0 ]; then
	echo "Created ${RELEASE_TAR}"
	if [ -n "${PKGBUILD_GPG_SIGN_AS}" ]; then
		echo "Created ${RELEASE_ASC}"
	fi
	echo "Created ${UPGRADE_TAR}"
	if [ -n "${PKGBUILD_GPG_SIGN_AS}" ]; then
		echo "Created ${UPGRADE_ASC}"
	fi
else
	echo "Bootstrap creation failed."
fi
exit $((${bsret} + ${chret}))
