#!/bin/bash

if [ $# -eq 1 ]; then
	chrootdir="${1%%/}"; shift
else
	echo "usage: $0 <chrootdir>" >&2
	exit 2
fi

if [ "$(uname -s)" != "Linux" ]; then
	echo "ERROR: Script is only suitable for Linux." >&2
	exit 1
fi

if [ -d ${chrootdir} ]; then
	#
	# Try a few times to unmount the sandbox, just in case there are any
	# lingering processes holding mounts open.
	#
	for retry in 1 2 3
	do
		${chrootdir}/sandbox umount >/dev/null 2>&1
		mounts=`mount -v | grep "${chrootdir}/"`
		if [ -z "${mounts}" ]; then
			rm -rf ${chrootdir}
			break
		else
			sleep 5
		fi
	done
fi
