#!/bin/bash
#
# Script to initiate a Jenkins build.
#
# The variable PKGBUILD is required to be set, and is normally set
# by the Jenkins environment.
#

if [ -z "${PKGBUILD}" ]; then
	echo "ERROR: Must set PKGBUILD in the environment" >&2
	exit 2
fi

#
# Load per-pkgbuild config
#
pkgconf="$(dirname $0)/../conf/${PKGBUILD}/pkgbuild.conf"
if [ -f ${pkgconf} ]; then
	. ${pkgconf}
else
	echo "ERROR: Could not find ${pkgconf}" >&2
	exit 1
fi

#
# Execute optional pre-build script
#
if [ -n "${JENKINS_PRE_BUILD}" ]; then
	. ${JENKINS_PRE_BUILD}
fi

#
# Sanity check that build hosts are running the expected platform image.
#
if [ -n "${PI_REQUIRED}" ]; then
	for ip in ${PBULK_CLIENTS}; do
		if [ "${PKGBUILD_OPSYS}" = "SunOS" ]; then
			hostpi=$(ssh ${ip} "uname -v")
		else
			hostpi=$(ssh ${ip} "uname -r")
		fi
		if [ "${hostpi}" != "${PI_REQUIRED}" ]; then
			echo "ERROR: ${ip} failed platform check, ${hostpi} != ${PI_REQUIRED}"
			exit 1
		fi
	done
fi

#
# Ensure, if signed packages are requested, that all build hosts can sign
# unattended.  This isn't perfect - ideally we'd test we can actually sign
# something, but we can't do that without creating chroots and that's a bit
# heavyweight - but testing for the gpg-agent socket (or a file which denotes
# the host doesn't use the agent) should do for now.
#
if [ -n "${PKGBUILD_GPG_SIGN_AS}" ]; then
	for ip in ${PBULK_CLIENTS}; do
		ssh ${ip} "test -f ${ROOT_HOMEDIR}/.gnupg/no-agent || " \
			  "pgrep gpg-agent >/dev/null"
		if [ $? -ne 0 ]; then
			echo "ERROR: ${ip} is not running gpg-agent"
			exit 1
		fi
	done
fi

#
# Set up cleanup handler to ensure chroots are removed for the next run.
#
cleanup()
{
	for dir in ${CHROOT_BASEDIR}/pkgsrc-${PKGBUILD}*; do
		if [ -d ${dir} ]; then
			echo "Removing ${dir} chroot..."
			${CHROOT_DELETE} ${dir}
		fi
	done
}
trap cleanup EXIT

#
# Perform the build.  Start with a cleanup to ensure any previous failed build
# is removed first (happens if e.g. the Java client disconnects).
#
mkdir -p ${CHROOT_BASEDIR}
cleanup
echo "Creating ${CHROOT_BASEDIR}/pkgsrc-${PKGBUILD} chroot..."
${CHROOT_CREATE} ${CHROOT_BASEDIR}/pkgsrc-${PKGBUILD}
env -i ${CMD_CHROOT} ${CHROOT_BASEDIR}/pkgsrc-${PKGBUILD} ${CMD_SHELL} -c "
	export HOME=${ROOT_HOMEDIR}
	export PATH=${PBULK_PATH}
	echo 'Running bulkbuild${PBULK_RESTART:+-restart} using' \
	    '${PKGBUILD_BASEDIR}/conf/${PKGBUILD}/pbulk.conf'
	${PBULK_BASEDIR}/bin/bulkbuild${PBULK_RESTART:+-restart} \
	    ${PKGBUILD_BASEDIR}/conf/${PKGBUILD}/pbulk.conf
"
#
# Save the return code of the bulkbuild run so we can correctly report
# success/failure back to Jenkins.
#
ret=$?

#
# Attempt to automatically report scan failures.
#
if [ $ret -ne 0 ]; then
	presolve_err=${BULKLOG_BASEDIR}/${BULKLOG_DIR}/meta/presolve-err.log
	pscan_err=${BULKLOG_BASEDIR}/${BULKLOG_DIR}/meta/pscan.stderr
	presolve_match=/tmp/presolve-match-$$.txt
	pscan_match=/tmp/pscan-match-$$.txt

	# Only look for certain strings, there is lots of unnecessary output
	# we need to ignore.
	grep "No.match" ${presolve_err} >${presolve_match} 2>/dev/null
	grep -v Duplicate ${pscan_err} >${pscan_match} 2>/dev/null

	if [ -s ${presolve_match} ]; then

		# Output for Jenkins logs
		cat ${presolve_match}

		# Report failures to interested parties.
		(
			printf "The following unresolvable dependencies are "
			printf "preventing bulk builds\n"
			printf "from running:\n\n"
			cat ${presolve_match}
			if [ -s ${pscan_match} ]; then
				printf "\n"
				printf "Additional pscan.stderr output:\n\n"
				cat ${pscan_match}
			fi
		) | ${PKGBUILD_BASEDIR}/scripts/mail-report \
		    -s "Scan failure for ${PKGBUILD} bulk build" \
		    ${FAILURE_RECIPIENTS}
	fi
	rm -f ${presolve_match} ${pscan_match}
fi

#
# Execute optional post-build script
#
if [ -n "${JENKINS_POST_BUILD}" ]; then
	. ${JENKINS_POST_BUILD}
	ret=$((ret+$?))
fi

if [ $ret -ne 0 ]; then
	# Wait a little while on failure to ensure the chroot is unused.
	sleep 10
fi

cleanup
exit ${ret}
